<?php
/**
 *  View for Settings controller
 *  Copernica Marketing Software
 *  http://www.copernica.com
 */
?>

<div class="content-header">
    <h3 class="icon-head head-system-account">
        <?php echo $this->__("Copernica Marketing Software : Settings"); ?>
    </h3>
</div>

<form action="<?php echo $this->getPostUrl(); ?>" method="post" name="synchronize_form" id="synchronize_form">
    <div class="entry-edit">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend">
                <?php echo $this->__("Synchronization settings"); ?>
            </h4>
        </div>

        <div class="fieldset">
                <div class="hor-scroll">
                    <table cellspacing="0" class="form-list">
                        <tbody>
                            <tr>
                                <td class="label">
                                    <?php echo $this->__("Authorization"); ?>
                                </td>
                                <td>
                                    <?php
                                        if (!Mage::getStoreConfig('copernica_options/apiconnection/apiaccesstoken'))
                                        {
                                            echo $this->__("Magento is not authorized with a Copernica account.");
                                            ?>
                                                <br/>
                                                <a href="<?php echo $this->getAuthorizeURI(); ?>">
                                                    <?php echo $this->__("Authorize Magento with a Copernica account"); ?>
                                                </a>
                                            <?php
                                        }
                                        else
                                        {
                                               echo $this->__("Magento is authorized to account '%s'", Mage::getStoreConfig('copernica_options/apiconnection/apiaccount'));
                                            ?>
                                                <br/>
                                                <a href="<?php echo $this->getAuthorizeURI(); ?>">
                                                    <?php echo $this->__("Re-authorize to a different account");?>
                                                </a>
                                            <?php
                                        }
                                    ?>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</form>
