<?php
/**
 *  View for Settings controller
 *  Copernica Marketing Software
 *  http://www.copernica.com
 */

// get config into local scope
$_config = Mage::helper('integration/config');

?>

<script type="text/javascript">

// on page load
Event.observe(window, 'load', function() {

    // when button is clicked we want to save information on server
    $('synchronize_save').on('click', function(event) {
        $('synchronize_form').submit();
    });

    // when user want to sync only some of the store we want to show him list of
    // stores to filter
    $('stores-to-sync').on('change', function (event) {
        // we want to change only when proper radio is clicked
        if (!event.target.name || event.target.name != 'store-synchronize') return;

        // when 'some' radio is clicked we can show stores filter
        if (event.target.value == 'some') $('stores-filter').style.display = 'block';
        else $('stores-filter').style.display = 'none';
    });

}, false);

</script>

<div class="content-header">
    <h3 class="icon-head head-system-account">
        Copernica Marketing Software : Settings
    </h3>
    <p class="form-buttons">
        <button type="button" name="synchronize_save" id="synchronize_save">Save connection settings</button>
    </p>
</div>

<form action="<?php echo $this->getPostUrl(); ?>" method="post" name="synchronize_form" id="synchronize_form">
    <div class="entry-edit">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend">
                Synchronization settings
            </h4>
        </div>

        <div class="fieldset">
                <div class="hor-scroll">
                    <table cellspacing="0" class="form-list">
                        <tbody>
                            <tr>
                                <td class="label">Authorization</td>
                                <td>
                                    <?php
                                        if (!$_config->getAccessToken())
                                        {
                                            ?>
                                                Magento is not authorized with a Copernica account.<br>
                                                <a href="<?= $this->getAuthorizeURI(); ?>">Authorize magento with a Copernica account</a>
                                            <?php
                                        }
                                        else
                                        {
                                            ?>
                                               Magento is authorized to account '<?= $_config->getAccountName(); ?>'.<br>
                                                <a href="<?= $this->getAuthorizeURI(); ?>">Re-authorize to a different account</a>
                                            <?php
                                        }
                                    ?>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="entry-edit">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend">
                Stores settings
            </h4>
        </div>

        <div class="fieldset">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tbody>
                        <tr>
                            <td class="label">
                                Stores to synchronize
                            </td>
                            <td class="value" id="stores-to-sync">
                                <input type="radio" name="store-synchronize" id="store-synchronize-all" value="all"<?php if (is_null($_config->getEnabledStores())) { ?> checked <?php } ?>>
                                <label for="store-synchronize-all">Synchronize all stores</label><br>

                                <input type="radio" name="store-synchronize" id="store-synchronize-none" value="none"<?php if ($_config->getEnabledStores() === array()) { ?> checked <?php } ?>>
                                <label for="store-synchronize-none">Disable synchronization</label><br>

                                <input type="radio" name="store-synchronize" id="store-synchronize-some" value="some"<?php if ($_config->getEnabledStores()) { ?> checked <?php } ?>>
                                <label for="store-synchronize-some">Synchronize some stores</label><br>

                                <br>
                                <div id="stores-filter" <?php if ($_config->getEnabledStores() || $_config->getEnabledStores() !== array()) { ?> style="display: none;" <?php } ?>>
                                    <?php
                                        foreach(Mage::app()->getWebsites() as $website){
                                            foreach($website->getGroups() as $group){
                                                foreach($group->getStores() as $store) {

                                                    $enabledStore = is_array($_config->getEnabledStores()) && in_array($store->getId(), $_config->getEnabledStores());

                                                    ?>
                                                        <input type="checkbox" name="store[]" id="chk-store-<?= $store->getId(); ?>" value="<?= $store->getId(); ?>" <?php if ($enabledStore) { ?> checked="checked" <?php } ?>>
                                                        <label for="chk-store-<?= $store->getId(); ?>">
                                                            <?= $website->getName().' > '.$group->getName().' > '.$store->getName(); ?>
                                                        </label>
                                                        <br>
                                                    <?php
                                                }
                                            }
                                        }
                                    ?>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</form>
